{% set name = "zarray" %}
{% set version = "0.0.2" %}
{% set sha256 = "8492e5d903e41f69d6eacdc8b616eb19f982d215c83812e17db3dff51ae6c6fb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xtensor-stack/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - xtensor >=0.21.9
  run:
    # header-only packages don't have
    # a run_exports section
    - {{ pin_compatible('xtensor', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/zarray  # [unix]
    - test -f ${PREFIX}/include/zarray/zarray.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/zarray/zarrayConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/zarray/zarrayConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\zarray\zarray.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\zarray\zarrayConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\zarray\zarrayConfigVersion.cmake (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Dynamically typed N-D expression system based on xtensor
  description: Dynamically typed N-D expression system based on xtensor.
  doc_url: http://zarray.readthedocs.io
  dev_url: https://github.com/xtensor-stack/zarray

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
    - JohanMabille
    - conda-forge/xtensor
